# Generated by Django 5.0.4 on 2024-06-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar_color',
            field=models.CharField(default='#abcdef', max_length=7),
            preserve_default=False,
        ),
    ]
