# Generated by Django 4.2.16 on 2024-11-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('due_to', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('priority', models.TextField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('URGENT', 'Urgent')])),
                ('category', models.TextField(choices=[('TECHNICAL_TASK', 'Technical Task'), ('USER_STORY', 'User Story')])),
                ('status', models.TextField(choices=[('TO_DO', 'To Do'), ('AWAIT_FEEDBACK', 'Await Feedback'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')])),
            ],
        ),
    ]
