# Generated by Django 5.0.4 on 2024-06-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('dueTo', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('priority', models.TextField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('URGENT', 'Urgent')])),
                ('category', models.TextField(choices=[('TECHNICAL_TASK', 'Technical Task'), ('USER_STORY', 'User Story')])),
                ('status', models.TextField(choices=[('TO_DO', 'To Do'), ('AWAIT_FEEDBACK', 'Await Feedback'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')])),
                ('contacts', models.ManyToManyField(related_name='tasks', to='contact.contact')),
            ],
        ),
    ]
