# Generated by Django 5.0.4 on 2024-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_avatar_color'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(default=None, related_name='tasks', to='contact.contact'),
        ),
    ]
